[tools]
java = ["17", "11", "8"]
python = "3.12"
node = "20"
go = "1.23"
rust = "1.81"

[env]
JAVA_HOME = "{{ ~/.local/share/mise/installs/java/17 }}"
GOPATH = "{{ env.HOME }}/.local/share/go"
CARGO_HOME = "{{ env.HOME }}/.local/share/cargo"

[settings]
experimental = true
