format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = false
scan_timeout = 10

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""

[git_status]
disabled = false

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
