#!/usr/bin/env bash
# Interactive language and version selector for the Neovim IDE.
#
# Lets the user choose which programming languages to configure AND which
# runtime versions to install.  Versions are queried dynamically from mise
# (mise ls-remote) — no static version lists are stored anywhere.
#
# Multiple versions per language are supported.  The selection is saved to
# ~/.local/share/nvim/languages.local in key=value format:
#
#   # Languages configured for this machine.
#   python=3.14,3.13
#   java=25,21,17
#   typescript=24,22
#   go=1.26,1.24
#   cpp=system
#   rust=1.97,1.95
#
# The first version listed is the primary (default) version.  Additional
# versions are installed side-by-side via mise.
#
# Safe to re-run: existing selections are preserved, the user can add or
# remove languages or change versions at any time without affecting other
# settings.
#
# Usage:
#   scripts/languages.sh              # interactive
#   scripts/languages.sh --list       # print current selection and exit
#   scripts/languages.sh --all        # select all languages (latest stable)
#   scripts/languages.sh --regenerate # regenerate mise.toml from selection

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$REPO_ROOT/.." && pwd)"
NVIM_DATA_DIR="${NVIM_DATA_DIR:-$HOME/.local/share/nvim}"
LANGUAGES_FILE="$NVIM_DATA_DIR/languages.local"

# All languages the IDE can configure.
# Format: "lang:display:mise_tool:default_version:dedup_mode:keep_count"
#   lang            — module name in lua/languages/
#   display         — human-readable name shown in the menu
#   mise_tool       — mise tool name (for version lookup), or "system"/"none"
#   default_version — fallback version when mise is unavailable
#   dedup_mode      — "major" (dedup by major number, e.g. 21 from 21.0.2)
#                     "minor" (dedup by major.minor, e.g. 3.14 from 3.14.5)
#                     "none"  (no version list — system toolchain)
#   keep_count      — how many distinct versions to offer (10)
ALL_LANGUAGES=(
  "python:Python:python:3.14:minor:10"
  "java:Java:java:25:major:10"
  "typescript:TypeScript/JS:node:24:major:10"
  "go:Go:go:1.26:minor:10"
  "cpp:C/C++:system:system:none:0"
  "rust:Rust:rust:1.97:minor:10"
)

mkdir -p "$NVIM_DATA_DIR"

log() {
  printf '[languages] %s\n' "$*"
}

# ---------------------------------------------------------------------------
# Read / write selection (key=value format, comma-separated versions)
# ---------------------------------------------------------------------------

# Returns the version(s) for a language, or empty if not selected.
# Multiple versions are comma-separated: "3.14,3.13"
get_language_version() {
  local lang="$1"
  if [[ -f "$LANGUAGES_FILE" ]]; then
    grep -E "^${lang}=" "$LANGUAGES_FILE" 2>/dev/null | head -1 | cut -d= -f2-
  fi
}

# Returns the primary (first) version for a language.
get_primary_version() {
  local lang="$1"
  local versions
  versions=$(get_language_version "$lang")
  [[ -z "$versions" ]] && return 0
  echo "${versions%%,*}"
}

# Returns 0 if the language is selected, 1 otherwise.
is_selected() {
  local lang="$1"
  grep -qE "^${lang}=" "$LANGUAGES_FILE" 2>/dev/null
}

# Returns all selected languages (one per line).
read_languages() {
  if [[ -f "$LANGUAGES_FILE" ]]; then
    grep -E '^[a-z]+=' "$LANGUAGES_FILE" 2>/dev/null | cut -d= -f1
  fi
}

# Write the full selection file.
# Arguments: pairs of "lang=version" strings.
write_selection() {
  local entries=("$@")
  {
    echo "# Languages and versions configured for this machine."
    echo "# Generated by dotfiles/scripts/languages.sh"
    echo "# Format: language=version[,version,...]"
    echo "# First version is the primary. Edit manually or re-run the selector."
    echo ""
    for entry in "${entries[@]}"; do
      [[ -z "$entry" ]] && continue
      echo "$entry"
    done
  } > "$LANGUAGES_FILE"
  log "Saved selection to $LANGUAGES_FILE"
}

# ---------------------------------------------------------------------------
# Dynamic version discovery via mise
# ---------------------------------------------------------------------------

# Extract the dedup key from a version string based on the dedup mode.
#   "major" → just the major number (e.g. "21" from "21.0.2")
#   "minor" → major.minor (e.g. "3.14" from "3.14.5")
version_key() {
  local version="$1"
  local mode="$2"
  case "$mode" in
    major) echo "${version%%.*}" ;;
    minor)
      local major="${version%%.*}"
      local rest="${version#*.}"
      echo "${major}.${rest%%.*}"
      ;;
    *) echo "$version" ;;
  esac
}

# Query mise for available versions of a tool.
# Prints the most recent stable versions deduplicated by the given mode.
# Keeps the last N distinct version keys (showing the dedup key, e.g. "3.14"
# or "21", not the full patch version — mise resolves the latest patch
# automatically when given a major or major.minor specifier).
# If mise is not installed, returns the fallback version.
list_versions() {
  local tool="$1"
  local fallback="$2"
  local dedup_mode="${3:-minor}"
  local keep="${4:-10}"

  if [[ "$dedup_mode" == "none" ]]; then
    echo "$fallback"
    return 0
  fi

  if ! command -v mise >/dev/null 2>&1; then
    echo "$fallback"
    return 0
  fi

  local versions
  if [[ "$tool" == "java" ]]; then
    # Java: only plain numeric versions (skip distro-prefixed like zulu-, temurin-)
    versions=$(mise ls-remote "$tool" 2>/dev/null | grep -E '^[0-9]' | grep -vE '(alpha|beta|rc|dev|pre|ea)' || true)
  else
    versions=$(mise ls-remote "$tool" 2>/dev/null | grep -E '^[0-9]' | grep -vE '(alpha|beta|rc|dev|pre|nightly|a[0-9]|b[0-9])' || true)
  fi

  if [[ -z "$versions" ]]; then
    echo "$fallback"
    return 0
  fi

  # Deduplicate by the dedup key — keep the first occurrence (latest patch
  # for that key, since ls-remote is sorted ascending and the last entry for
  # each key is the newest).
  local seen=""
  local result=()
  while IFS= read -r v; do
    [[ -z "$v" ]] && continue
    local key
    key=$(version_key "$v" "$dedup_mode")
    if [[ " $seen " != *" $key "* ]]; then
      seen="$seen $key"
      result+=("$key")
    fi
  done <<< "$versions"

  # Print the last N keys (most recent)
  local start=0
  if [[ ${#result[@]} -gt "$keep" ]]; then
    start=$(( ${#result[@]} - keep ))
  fi
  for (( i=start; i<${#result[@]}; i++ )); do
    echo "${result[$i]}"
  done
}

# ---------------------------------------------------------------------------
# Menu drawing helpers
# ---------------------------------------------------------------------------

LANG_MENU_WIDTH=60

# Horizontal rule of LANG_MENU_WIDTH box dashes between two corner glyphs.
menu_rule() {
  printf '  %s' "$1"
  local n=0
  while (( n++ < LANG_MENU_WIDTH )); do printf '─'; done
  printf '%s\n' "$2"
}

# A text row padded to LANG_MENU_WIDTH between two vertical glyphs.
menu_row() {
  printf '  │%-*s│\n' "$LANG_MENU_WIDTH" "$1"
}

# ---------------------------------------------------------------------------
# Interactive version picker (multi-select)
# ---------------------------------------------------------------------------

# Prompts the user to pick one or more versions.
# Arguments: tool display fallback [current_versions] [dedup_mode] [keep]
pick_version() {
  local tool="$1"
  local display="$2"
  local fallback="$3"
  local current_versions="${4:-}"
  local dedup_mode="${5:-minor}"
  local keep="${6:-10}"

  local versions=()
  while IFS= read -r v; do
    versions+=("$v")
  done < <(list_versions "$tool" "$fallback" "$dedup_mode" "$keep")

  # Parse current selections into an associative-like lookup
  local current_list=()
  IFS=',' read -ra current_list <<< "$current_versions"

  local default="$fallback"
  [[ -n "$current_versions" ]] && default="$current_versions"

  echo "" >&2
  echo "  ${display} - available versions (via mise):" >&2
  echo "" >&2
  if [[ ${#versions[@]} -eq 0 ]]; then
    echo "    (mise returned no versions; using ${default})" >&2
  fi

  # Show versions with mark for currently selected
  local i=1
  for v in "${versions[@]}"; do
    local mark=" "
    for cv in "${current_list[@]}"; do
      if [[ "$v" == "$cv" ]]; then
        mark="*"
        break
      fi
    done
    printf '  %s %d. %-10s\n' "$mark" "$i" "$v" >&2
    i=$((i + 1))
  done

  echo "" >&2
  echo "  Pick: number, comma-list (1,3,5), exact version, or Enter to keep." >&2
  echo "  Current: ${default}" >&2
  read -rp "  > " choice

  if [[ -z "$choice" ]]; then
    echo "$default"
    return
  fi

  # Comma-separated numbers → build version list
  if [[ "$choice" =~ ^[0-9,]+$ ]] && [[ "$choice" == *,* ]]; then
    local result=""
    IFS=',' read -ra nums <<< "$choice"
    for num in "${nums[@]}"; do
      num=$(echo "$num" | tr -d ' ')
      if [[ "$num" =~ ^[0-9]+$ ]] && [[ "$num" -ge 1 ]] && [[ "$num" -le ${#versions[@]} ]]; then
        local v="${versions[$((num - 1))]}"
        [[ -n "$result" ]] && result+=","
        result+="$v"
      fi
    done
    if [[ -n "$result" ]]; then
      echo "$result"
      return
    fi
  fi

  # Single number
  if [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le ${#versions[@]} ]]; then
    echo "${versions[$((choice - 1))]}"
    return
  fi

  # Exact version string (may be comma-separated custom versions)
  echo "$choice"
}

# ---------------------------------------------------------------------------
# Selection helpers
# ---------------------------------------------------------------------------

# Parse one ALL_LANGUAGES entry into PE_* globals.
# Format: "lang:display:mise_tool:default_version:dedup_mode:keep_count"
parse_entry() {
  local entry="$1"
  PE_LANG="${entry%%:*}"
  local rest="${entry#*:}"
  PE_DISPLAY="${rest%%:*}"
  rest="${rest#*:}"
  PE_MISE_TOOL="${rest%%:*}"
  rest="${rest#*:}"
  PE_FALLBACK="${rest%%:*}"
  rest="${rest#*:}"
  PE_DEDUP="${rest%%:*}"
  PE_KEEP="${rest##*:}"
}

# Insert or replace a language's version(s) in the selection file.
set_language_version() {
  local lang="$1"
  local version="$2"
  local entries=()
  local found=false
  while IFS= read -r l; do
    [[ -z "$l" ]] && continue
    if [[ "$l" == "$lang" ]]; then
      entries+=("${lang}=${version}")
      found=true
    else
      entries+=("${l}=$(get_language_version "$l")")
    fi
  done < <(read_languages)
  if [[ "$found" == false ]]; then
    entries+=("${lang}=${version}")
  fi
  write_selection "${entries[@]}"
}

# Open the version picker for a language and save the chosen version(s).
configure_language() {
  local num="$1"
  parse_entry "${ALL_LANGUAGES[$((num - 1))]}"

  local version
  if [[ "$PE_MISE_TOOL" == "system" || "$PE_MISE_TOOL" == "none" ]]; then
    version="$PE_FALLBACK"
    log "${PE_DISPLAY} uses the system toolchain -> ${version}"
  else
    version=$(pick_version "$PE_MISE_TOOL" "$PE_DISPLAY" "$PE_FALLBACK" "$(get_language_version "$PE_LANG")" "$PE_DEDUP" "$PE_KEEP")
  fi
  set_language_version "$PE_LANG" "$version"
}

# Remove a language from the selection.
remove_language() {
  local num="$1"
  parse_entry "${ALL_LANGUAGES[$((num - 1))]}"
  if ! is_selected "$PE_LANG"; then
    log "${PE_DISPLAY} is not selected."
    return 0
  fi
  local entries=()
  while IFS= read -r l; do
    [[ -z "$l" ]] && continue
    [[ "$l" != "$PE_LANG" ]] && entries+=("${l}=$(get_language_version "$l")")
  done < <(read_languages)
  write_selection "${entries[@]}"
}

# Select every language at its fallback (latest stable) version.
select_all_latest() {
  local entries=()
  for entry in "${ALL_LANGUAGES[@]}"; do
    parse_entry "$entry"
    entries+=("${PE_LANG}=${PE_FALLBACK}")
  done
  write_selection "${entries[@]}"
}

# ---------------------------------------------------------------------------
# Interactive menu
# ---------------------------------------------------------------------------

show_menu() {
  echo ""
  menu_rule '┌' '┐'
  menu_row " Language & Version Setup - Neovim IDE"
  menu_rule '├' '┤'
  menu_row " Always available (no setup needed):"
  menu_row "   JSON, YAML, TOML, Bash, Lua, Markdown"
  menu_rule '├' '┤'
  menu_row " <N>    choose / change a language's version(s)"
  menu_row " r<N>    remove a language      a = all   n = clear all"
  menu_row " Enter   finish selection"
  menu_rule '└' '┘'
  echo ""

  local i=1
  for entry in "${ALL_LANGUAGES[@]}"; do
    parse_entry "$entry"
    local mark=" "
    local version_info="-"
    if is_selected "$PE_LANG"; then
      mark="x"
      version_info="$(get_language_version "$PE_LANG")"
    fi
    printf '  [%s] %2d. %-16s %s\n' "$mark" "$i" "$PE_DISPLAY" "$version_info"
    i=$((i + 1))
  done
  echo ""
  printf '  Choose a language (1-%d), or Enter to finish.\n' "${#ALL_LANGUAGES[@]}"
}

interactive() {
  while true; do
    show_menu
    read -rp "  > " choice

    if [[ -z "$choice" ]]; then
      break
    elif [[ "$choice" == "a" || "$choice" == "A" ]]; then
      select_all_latest
      continue
    elif [[ "$choice" == "n" || "$choice" == "N" ]]; then
      write_selection ""
      continue
    elif [[ "$choice" =~ ^[rR][0-9]+$ ]]; then
      local num="${choice:1}"
      remove_language "$num"
      continue
    elif [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le ${#ALL_LANGUAGES[@]} ]]; then
      configure_language "$choice"
      continue
    else
      log "Invalid choice: $choice (try a number, r<N>, a, n, or Enter)"
    fi
  done
}

# ---------------------------------------------------------------------------
# Generate mise.toml from the selection
# ---------------------------------------------------------------------------

generate_mise_toml() {
  local mise_file="$DOTFILES_ROOT/mise.toml"
  local has_mise=false
  command -v mise >/dev/null 2>&1 && has_mise=true

  # Determine which env vars to emit based on the selection
  local has_java=false has_go=false has_rust=false
  while IFS= read -r l; do
    [[ -z "$l" ]] && continue
    case "$l" in
      java*)     has_java=true ;;
      go*)       has_go=true ;;
      rust*)     has_rust=true ;;
    esac
  done < <(read_languages)

  {
    echo "# Generated by dotfiles/scripts/languages.sh from languages.local"
    echo "# Do not edit manually — re-run the language selector to change."
    echo ""
    echo "[tools]"
  } > "$mise_file"

  # Read selected languages and build [tools] section
  # Multiple versions are comma-separated → mise array syntax ["v1", "v2"]
  while IFS='=' read -r lang versions; do
    [[ "$lang" =~ ^# ]] && continue
    [[ -z "$lang" ]] && continue

    # Split versions into array
    local version_array=()
    IFS=',' read -ra version_array <<< "$versions"

    # Build mise array syntax: ["3.14", "3.13"]
    local mise_versions=""
    for v in "${version_array[@]}"; do
      [[ -n "$mise_versions" ]] && mise_versions+=", "
      mise_versions+="\"${v}\""
    done

    case "$lang" in
      python|java|node|go|rust)
        echo "${lang} = [${mise_versions}]" >> "$mise_file"
        ;;
      typescript)
        # TypeScript uses Node.js as its runtime
        echo "node = [${mise_versions}]" >> "$mise_file"
        ;;
      cpp)
        # C/C++ uses system clangd, no mise runtime
        ;;
      *)
        echo "# Unknown: ${lang}=${versions}" >> "$mise_file"
        ;;
    esac
  done < "$LANGUAGES_FILE" 2>/dev/null || true

  {
    echo ""
    echo "[env]"
    # JAVA_HOME: use mise's built-in tool path resolver.  {{ tools.java.path }}
    # resolves to the primary (first) java version in [tools] above.
    if [[ "$has_java" == true ]]; then
      echo "JAVA_HOME = { value = \"{{ tools.java.path }}\", tools = true }"
    fi
    if [[ "$has_go" == true ]]; then
      echo "GOPATH = \"{{ env.HOME }}/.local/share/go\""
    fi
    if [[ "$has_rust" == true ]]; then
      echo "CARGO_HOME = \"{{ env.HOME }}/.local/share/cargo\""
    fi
    echo ""
    echo "[settings]"
    echo "experimental = true"
  } >> "$mise_file"

  log "Generated $mise_file"

  # Install mise runtimes
  if [[ "$has_mise" == true ]]; then
    log "Installing mise runtimes..."
    mise install 2>/dev/null || true
  fi
}

# ---------------------------------------------------------------------------
# Install tools for selected languages
# ---------------------------------------------------------------------------

install_tools() {
  local tool_script="$DOTFILES_ROOT/../nvim-config/scripts/install-tools.sh"
  if [[ -x "$tool_script" ]]; then
    log "Installing tools for selected languages..."
    "$tool_script"
  else
    log "install-tools.sh not found at $tool_script"
    log "Tools can be installed manually. See nvim-config/docs/languages.md"
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
  case "${1:-}" in
    --list)
      echo "Selected languages:"
      if [[ -f "$LANGUAGES_FILE" ]] && grep -qE '^[a-z]+=' "$LANGUAGES_FILE" 2>/dev/null; then
        cat "$LANGUAGES_FILE" | grep -E '^[a-z]+='
      else
        echo "  (none — run 'scripts/languages.sh' to select)"
      fi
      return 0
      ;;
    --all)
      select_all_latest
      generate_mise_toml
      install_tools
      return 0
      ;;
    --regenerate)
      if [[ ! -f "$LANGUAGES_FILE" ]]; then
        log "No languages.local found — nothing to regenerate."
        log "Run: scripts/languages.sh"
        return 1
      fi
      generate_mise_toml
      install_tools
      return 0
      ;;
    --help|-h)
      echo "Usage: languages.sh [--list|--all|--regenerate|--help]"
      echo ""
      echo "  (no args)     Interactive language + version selection menu"
      echo "  --list       Print currently selected languages and versions"
      echo "  --all        Select all languages (latest stable) and install"
      echo "  --regenerate Regenerate mise.toml from existing selection (no menu)"
      echo ""
      echo "Multiple versions: pick comma-separated numbers (e.g. 1,3,5)"
      echo "  in the version picker to install multiple versions side-by-side."
      echo "  The first version is the primary (default) version."
      return 0
      ;;
  esac

  interactive
  generate_mise_toml
  install_tools

  log "Done. Restart Neovim and your shell for changes to take effect."
  if [[ -f "$LANGUAGES_FILE" ]] && grep -qE '^[a-z]+=' "$LANGUAGES_FILE" 2>/dev/null; then
    log "  Selected:"
    grep -E '^[a-z]+=' "$LANGUAGES_FILE" | sed 's/^/    /'
  fi
}

main "$@"
