#!/usr/bin/env bash
# Interactive language and version selector for the Neovim IDE.
#
# Lets the user choose which programming languages to configure AND which
# runtime versions to install.  Versions are queried dynamically from mise
# (mise ls-remote) — no static version lists are stored anywhere.
#
# The selection is saved to ~/.local/share/nvim/languages.local in a simple
# key=value format:
#
#   # Languages configured for this machine.
#   python=3.12.7
#   java=17
#   typescript=20.18.0
#   go=1.23.3
#   cpp=system
#   rust=1.81.0
#
# Safe to re-run: existing selections are preserved, the user can add or
# remove languages or change versions at any time without affecting other
# settings.
#
# Usage:
#   scripts/languages.sh          # interactive
#   scripts/languages.sh --list   # print current selection and exit
#   scripts/languages.sh --all    # select all languages (latest stable)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$REPO_ROOT/.." && pwd)"
NVIM_DATA_DIR="${NVIM_DATA_DIR:-$HOME/.local/share/nvim}"
LANGUAGES_FILE="$NVIM_DATA_DIR/languages.local"

# All languages the IDE can configure.
# Format: "lang:display:mise_tool:default_version_query"
#   lang                 — module name in lua/languages/
#   display              — human-readable name shown in the menu
#   mise_tool           — mise tool name (for version lookup), or "none"
#   default_version_query — what to show as the suggested default
ALL_LANGUAGES=(
  "python:Python:python:3.12"
  "java:Java:java:17"
  "typescript:TypeScript/JS:node:20"
  "go:Go:go:1.23"
  "cpp:C/C++:system:system"
  "rust:Rust:rust:1.81"
)

mkdir -p "$NVIM_DATA_DIR"

log() {
  printf '[languages] %s\n' "$*"
}

# ---------------------------------------------------------------------------
# Read / write selection (key=value format)
# ---------------------------------------------------------------------------

# Returns the version for a language, or empty if not selected.
get_language_version() {
  local lang="$1"
  if [[ -f "$LANGUAGES_FILE" ]]; then
    grep -E "^${lang}=" "$LANGUAGES_FILE" 2>/dev/null | head -1 | cut -d= -f2-
  fi
}

# Returns 0 if the language is selected, 1 otherwise.
is_selected() {
  local lang="$1"
  grep -qE "^${lang}=" "$LANGUAGES_FILE" 2>/dev/null
}

# Returns all selected languages (one per line).
read_languages() {
  if [[ -f "$LANGUAGES_FILE" ]]; then
    grep -E '^[a-z]+=' "$LANGUAGES_FILE" 2>/dev/null | cut -d= -f1
  fi
}

# Write the full selection file.
# Arguments: pairs of "lang=version" strings.
write_selection() {
  local entries=("$@")
  {
    echo "# Languages and versions configured for this machine."
    echo "# Generated by dotfiles/scripts/languages.sh"
    echo "# Format: language=version"
    echo "# Edit manually or re-run the selector to change."
    echo ""
    for entry in "${entries[@]}"; do
      echo "$entry"
    done
  } > "$LANGUAGES_FILE"
  log "Saved selection to $LANGUAGES_FILE"
}

# ---------------------------------------------------------------------------
# Dynamic version discovery via mise
# ---------------------------------------------------------------------------

# Query mise for available versions of a tool.
# Prints the most recent stable versions (last 15, deduplicated by minor).
# If mise is not installed, returns the fallback version.
list_versions() {
  local tool="$1"
  local fallback="$2"

  if ! command -v mise >/dev/null 2>&1; then
    echo "$fallback"
    return 0
  fi

  local versions
  versions=$(mise ls-remote "$tool" 2>/dev/null | grep -E '^[0-9]' | grep -vE '(alpha|beta|rc|dev|pre)' | tail -30 || true)

  if [[ -z "$versions" ]]; then
    echo "$fallback"
    return 0
  fi

  # Deduplicate by major.minor — keep the latest patch for each
  local seen=""
  local result=()
  while IFS= read -r v; do
    local minor="${v%.*}"
    if [[ " $seen " != *" $minor "* ]]; then
      seen="$seen $minor"
      result+=("$v")
    fi
  done <<< "$versions"

  # Print the last 10 (most recent)
  local start=0
  if [[ ${#result[@]} -gt 10 ]]; then
    start=$(( ${#result[@]} - 10 ))
  fi
  for (( i=start; i<${#result[@]}; i++ )); do
    echo "${result[$i]}"
  done
}

# Interactive version picker.
# Prompts the user to select from available versions or enter a custom one.
pick_version() {
  local tool="$1"
  local display="$2"
  local fallback="$3"
  local current_version
  current_version=$(get_language_version "${ALL_LANGUAGES_ENTRY_LANG:-}")

  echo ""
  echo "  Available ${display} versions (querying mise):"

  local versions=()
  while IFS= read -r v; do
    versions+=("$v")
  done < <(list_versions "$tool" "$fallback")

  local i=1
  for v in "${versions[@]}"; do
    local mark=" "
    if [[ "$v" == "$current_version" ]]; then
      mark="*"
    fi
    printf "  [%s] %d. %s\n" "$mark" "$i" "$v"
    i=$((i + 1))
  done

  echo ""
  echo "  Enter a number, type a version string, or Enter for default ($fallback)."
  read -rp " > " choice

  if [[ -z "$choice" ]]; then
    echo "$fallback"
  elif [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le ${#versions[@]} ]]; then
    echo "${versions[$((choice - 1))]}"
  else
    # Treat as a literal version string
    echo "$choice"
  fi
}

# ---------------------------------------------------------------------------
# Interactive menu
# ---------------------------------------------------------------------------

show_menu() {
  echo ""
  echo "  ╔═══════════════════════════════════════════════════════════╗"
  echo "  ║          Language Selection for Neovim IDE                ║"
  echo "  ╠═══════════════════════════════════════════════════════════╣"
  echo "  ║  Common languages are always available:                   ║"
  echo "  ║    JSON, YAML, Bash, Lua, TOML, Markdown                  ║"
  echo "  ╠═══════════════════════════════════════════════════════════╣"
  echo "  ║  Toggle languages by number. 'v' to change version.       ║"
  echo "  ║  Press Enter when done.                                   ║"
  echo "  ╚═══════════════════════════════════════════════════════════╝"
  echo ""

  local i=1
  for entry in "${ALL_LANGUAGES[@]}"; do
    local lang="${entry%%:*}"
    local rest="${entry#*:}"
    local display="${rest%%:*}"
    local mark=" "
    local version_info=""
    if is_selected "$lang"; then
      mark="✓"
      version_info=" ($(get_language_version "$lang"))"
    fi
    printf "  [%s] %d. %-14s %s%s\n" "$mark" "$i" "$lang" "$display" "$version_info"
    i=$((i + 1))
  done

  echo ""
  echo "  Commands: number=toggle, v<number>=version, a=all, n=none, Enter=done"
}

interactive() {
  while true; do
    show_menu
    read -rp " > " choice

    if [[ -z "$choice" ]]; then
      break
    elif [[ "$choice" == "a" || "$choice" == "A" ]]; then
      local entries=()
      for entry in "${ALL_LANGUAGES[@]}"; do
        local lang="${entry%%:*}"
        local rest="${entry#*:}"
        local fallback="${rest##*:}"
        entries+=("${lang}=${fallback}")
      done
      write_selection "${entries[@]}"
      return
    elif [[ "$choice" == "n" || "$choice" == "N" ]]; then
      write_selection ""
      return
    elif [[ "$choice" == v* ]]; then
      # Change version for a language
      local num="${choice#v}"
      if [[ "$num" =~ ^[0-9]+$ ]] && [[ "$num" -ge 1 ]] && [[ "$num" -le ${#ALL_LANGUAGES[@]} ]]; then
        local entry="${ALL_LANGUAGES[$((num - 1))]}"
        local lang="${entry%%:*}"
        local rest="${entry#*:}"
        local display="${rest%%:*}"
        local rest2="${rest#*:}"
        local mise_tool="${rest2%%:*}"
        local fallback="${rest2##*:}"

        ALL_LANGUAGES_ENTRY_LANG="$lang"
        local version
        version=$(pick_version "$mise_tool" "$display" "$fallback")

        # Update or add the language with the chosen version
        local entries=()
        local found=false
        while IFS= read -r l; do
          [[ -z "$l" ]] && continue
          if [[ "$l" == "$lang" ]]; then
            entries+=("${lang}=${version}")
            found=true
          else
            entries+=("${l}=$(get_language_version "$l")")
          fi
        done < <(read_languages)
        if [[ "$found" == false ]]; then
          entries+=("${lang}=${version}")
        fi
        write_selection "${entries[@]}"
      else
        log "Invalid language number: $num"
      fi
    elif [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le ${#ALL_LANGUAGES[@]} ]]; then
      local entry="${ALL_LANGUAGES[$((choice - 1))]}"
      local lang="${entry%%:*}"
      local rest="${entry#*:}"
      local rest2="${rest#*:}"
      local mise_tool="${rest2%%:*}"
      local fallback="${rest2##*:}"

      # Toggle: if selected, remove; if not selected, pick a version then add
      if is_selected "$lang"; then
        # Remove
        local entries=()
        while IFS= read -r l; do
          [[ -z "$l" ]] && continue
          [[ "$l" != "$lang" ]] && entries+=("${l}=$(get_language_version "$l")")
        done < <(read_languages)
        write_selection "${entries[@]}"
      else
        # Add with version selection
        ALL_LANGUAGES_ENTRY_LANG="$lang"
        local version
        version=$(pick_version "$mise_tool" "$(echo "$rest" | cut -d: -f1)" "$fallback")
        local entries=()
        while IFS= read -r l; do
          [[ -z "$l" ]] && continue
          entries+=("${l}=$(get_language_version "$l")")
        done < <(read_languages)
        entries+=("${lang}=${version}")
        write_selection "${entries[@]}"
      fi
    else
      log "Invalid choice: $choice"
    fi
  done
}

# ---------------------------------------------------------------------------
# Generate mise.toml from the selection
# ---------------------------------------------------------------------------

generate_mise_toml() {
  local mise_file="$DOTFILES_ROOT/mise.toml"
  local has_mise=false
  command -v mise >/dev/null 2>&1 && has_mise=true

  {
    echo "# Generated by dotfiles/scripts/languages.sh from languages.local"
    echo "# Do not edit manually — re-run the language selector to change."
    echo ""
    echo "[tools]"
  } > "$mise_file"

  # Read selected languages and build [tools] section
  while IFS='=' read -r lang version; do
    [[ "$lang" =~ ^# ]] && continue
    [[ -z "$lang" ]] && continue
    case "$lang" in
      python|java|node|go|rust)
        echo "${lang} = \"${version}\"" >> "$mise_file"
        ;;
      typescript)
        # TypeScript uses Node.js as its runtime
        echo "node = \"${version}\"" >> "$mise_file"
        ;;
      cpp)
        # C/C++ uses system clangd, no mise runtime
        ;;
      *)
        echo "# Unknown: ${lang}=${version}" >> "$mise_file"
        ;;
    esac
  done < "$LANGUAGES_FILE" 2>/dev/null || true

  {
    echo ""
    echo "[env]"
    echo "JAVA_HOME = \"{{ ~/.local/share/mise/installs/java/17 }}\""
    echo "GOPATH = \"{{ env.HOME }}/.local/share/go\""
    echo "CARGO_HOME = \"{{ env.HOME }}/.local/share/cargo\""
    echo ""
    echo "[settings]"
    echo "experimental = true"
  } >> "$mise_file"

  log "Generated $mise_file"

  # Install mise runtimes
  if [[ "$has_mise" == true ]]; then
    log "Installing mise runtimes..."
    mise install 2>/dev/null || true
  fi
}

# ---------------------------------------------------------------------------
# Install tools for selected languages
# ---------------------------------------------------------------------------

install_tools() {
  local tool_script="$DOTFILES_ROOT/../nvim-config/scripts/install-tools.sh"
  if [[ -x "$tool_script" ]]; then
    log "Installing tools for selected languages..."
    "$tool_script"
  else
    log "install-tools.sh not found at $tool_script"
    log "Tools can be installed manually. See nvim-config/docs/languages.md"
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
  case "${1:-}" in
    --list)
      echo "Selected languages:"
      if [[ -f "$LANGUAGES_FILE" ]] && grep -qE '^[a-z]+=' "$LANGUAGES_FILE" 2>/dev/null; then
        cat "$LANGUAGES_FILE" | grep -E '^[a-z]+='
      else
        echo "  (none — run 'scripts/languages.sh' to select)"
      fi
      return 0
      ;;
    --all)
      local entries=()
      for entry in "${ALL_LANGUAGES[@]}"; do
        local lang="${entry%%:*}"
        local rest="${entry#*:}"
        local fallback="${rest##*:}"
        entries+=("${lang}=${fallback}")
      done
      write_selection "${entries[@]}"
      generate_mise_toml
      install_tools
      return 0
      ;;
    --help|-h)
      echo "Usage: languages.sh [--list|--all|--help]"
      echo ""
      echo "  (no args)  Interactive language + version selection menu"
      echo "  --list    Print currently selected languages and versions"
      echo "  --all     Select all languages (latest stable) and install"
      return 0
      ;;
  esac

  interactive
  generate_mise_toml
  install_tools

  log "Done. Restart Neovim and your shell for changes to take effect."
  if [[ -f "$LANGUAGES_FILE" ]] && grep -qE '^[a-z]+=' "$LANGUAGES_FILE" 2>/dev/null; then
    log "  Selected:"
    grep -E '^[a-z]+=' "$LANGUAGES_FILE" | sed 's/^/    /'
  fi
}

main "$@"
