#!/usr/bin/env bash
# Interactive language selector for the Neovim IDE.
#
# Lets the user choose which programming languages to configure, saves the
# selection to ~/.local/share/nvim/languages.local, and installs the
# corresponding external tools.
#
# Safe to re-run: existing selections are preserved, the user can add or
# remove languages at any time.
#
# Usage:
#   scripts/languages.sh          # interactive
#   scripts/languages.sh --list   # print current selection and exit
#   scripts/languages.sh --all    # select all languages and install

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$REPO_ROOT/.." && pwd)"
NVIM_DATA_DIR="${NVIM_DATA_DIR:-$HOME/.local/share/nvim}"
LANGUAGES_FILE="$NVIM_DATA_DIR/languages.local"

# All languages the IDE can configure.
# Common languages (json, yaml, bash, lua, toml, markdown) are always on
# and are NOT listed here.
ALL_LANGUAGES=(
  "python:Python — basedpyright, ruff, pytest, debugpy"
  "java:Java — jdtls, lombok, google-java-format, Maven/Gradle, JUnit"
  "typescript:TypeScript/JS — typescript-language-server, prettier"
  "go:Go — gopls, goimports, delve"
  "cpp:C/C++ — clangd, clang-format"
  "rust:Rust — rust-analyzer, rustfmt, cargo"
)

mkdir -p "$NVIM_DATA_DIR"

log() {
  printf '[languages] %s\n' "$*"
}

# ---------------------------------------------------------------------------
# Read current selection
# ---------------------------------------------------------------------------

read_selection() {
  local result=()
  if [[ -f "$LANGUAGES_FILE" ]]; then
    while IFS= read -r line; do
      line="${line%%#*}"
      line="$(echo "$line" | xargs)"
      [[ -n "$line" ]] && result+=("$line")
    done < "$LANGUAGES_FILE"
  fi
  printf '%s\n' "${result[@]}"
}

is_selected() {
  local lang="$1"
  local current
  current=$(read_selection)
  echo "$current" | grep -qx "$lang" 2>/dev/null
}

# ---------------------------------------------------------------------------
# Write selection
# ---------------------------------------------------------------------------

write_selection() {
  local langs=("$@")
  {
    echo "# Languages configured for this machine."
    echo "# Generated by dotfiles/scripts/languages.sh"
    echo "# Edit manually or re-run the selector to change."
    echo ""
    for lang in "${langs[@]}"; do
      echo "$lang"
    done
  } > "$LANGUAGES_FILE"
  log "Saved selection to $LANGUAGES_FILE"
}

# ---------------------------------------------------------------------------
# Interactive menu
# ---------------------------------------------------------------------------

show_menu() {
  echo ""
  echo "  ╔═══════════════════════════════════════════════════════════╗"
  echo "  ║          Language Selection for Neovim IDE                ║"
  echo "  ╠═══════════════════════════════════════════════════════════╣"
  echo "  ║  Common languages are always available:                   ║"
  echo "  ║    JSON, YAML, Bash, Lua, TOML, Markdown                 ║"
  echo "  ╠═══════════════════════════════════════════════════════════╣"
  echo "  ║  Toggle languages by number. Press Enter when done.      ║"
  echo "  ╚═══════════════════════════════════════════════════════════╝"
  echo ""

  local i=1
  for entry in "${ALL_LANGUAGES[@]}"; do
    local lang="${entry%%:*}"
    local desc="${entry#*:}"
    local mark=" "
    if is_selected "$lang"; then
      mark="✓"
    fi
    printf "  [%s] %d. %-12s %s\n" "$mark" "$i" "$lang" "$desc"
    i=$((i + 1))
  done

  echo ""
  echo "  Enter a number to toggle, 'a' for all, 'n' for none, or Enter to confirm."
}

interactive() {
  while true; do
    show_menu
    read -rp " > " choice

    if [[ -z "$choice" ]]; then
      break
    elif [[ "$choice" == "a" || "$choice" == "A" ]]; then
      local all=()
      for entry in "${ALL_LANGUAGES[@]}"; do
        all+=("${entry%%:*}")
      done
      write_selection "${all[@]}"
      return
    elif [[ "$choice" == "n" || "$choice" == "N" ]]; then
      write_selection ""
      return
    elif [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le ${#ALL_LANGUAGES[@]} ]]; then
      local entry="${ALL_LANGUAGES[$((choice - 1))]}"
      local lang="${entry%%:*}"
      local current
      current=()
      while IFS= read -r line; do
        [[ -n "$line" ]] && current+=("$line")
      done < <(read_selection)

      # toggle
      local found=false
      local new=()
      for c in "${current[@]:-}"; do
        if [[ "$c" == "$lang" ]]; then
          found=true
        else
          new+=("$c")
        fi
      done
      if [[ "$found" == false ]]; then
        new+=("$lang")
      fi
      write_selection "${new[@]}"
    else
      log "Invalid choice: $choice"
    fi
  done
}

# ---------------------------------------------------------------------------
# Install tools for selected languages
# ---------------------------------------------------------------------------

install_tools() {
  local tool_script="$DOTFILES_ROOT/../nvim-config/scripts/install-tools.sh"
  if [[ -x "$tool_script" ]]; then
    log "Installing tools for selected languages..."
    "$tool_script"
  else
    log "install-tools.sh not found at $tool_script"
    log "Tools can be installed manually. See nvim-config/docs/languages.md"
  fi

  # Also run mise install for any new runtimes
  if command -v mise >/dev/null 2>&1; then
    log "Installing mise runtimes..."
    mise install 2>/dev/null || true
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
  case "${1:-}" in
    --list)
      echo "Selected languages:"
      if [[ -f "$LANGUAGES_FILE" ]]; then
        read_selection
      else
        echo "  (none — run 'scripts/languages.sh' to select)"
      fi
      return 0
      ;;
    --all)
      local all=()
      for entry in "${ALL_LANGUAGES[@]}"; do
        all+=("${entry%%:*}")
      done
      write_selection "${all[@]}"
      install_tools
      return 0
      ;;
    --help|-h)
      echo "Usage: languages.sh [--list|--all|--help]"
      echo ""
      echo "  (no args)  Interactive language selection menu"
      echo "  --list    Print currently selected languages"
      echo "  --all     Select all languages and install tools"
      return 0
      ;;
  esac

  interactive
  install_tools

  log "Done. Restart Neovim for changes to take effect."
  log "  Selected: $(read_selection | tr '\n' ' ')"
}

main "$@"
